const { PrismaClient } = require("@prisma/client");
const prisma = new PrismaClient();

async function main() {
  const properties = [
    {
      name: "Seaside Airstream",
      tagline: "Vintage trailer by the beach",
      category: "Airstream",
      image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750",
      country: "Australia",
      description: "A classic airstream trailer just steps from the water.",
      price: 180,
      guests: 2,
      bedrooms: 1,
      beds: 1,
      baths: 1,
      amenities: "Beach Access, WiFi, Kitchen",
      profileId: "user_2oTGLobcvLW3sFtiAuxuiRYL4Tq",
    },
    {
      name: "Luxury Tent Camp",
      tagline: "Glamping experience in the wild",
      category: "Tent",
      image: "https://images.unsplash.com/photo-1559099430-b65e5e5440a6",
      country: "South Africa",
      description: "A luxury tent with an amazing safari view.",
      price: 250,
      guests: 4,
      bedrooms: 2,
      beds: 2,
      baths: 1,
      amenities: "Safari Tours, Pool, WiFi",
      profileId: "user_2oTGLobcvLW3sFtiAuxuiRYL4Tq",
    },
    {
      name: "Urban Warehouse Loft",
      tagline: "Stylish industrial living",
      category: "Warehouse",
      image: "https://images.unsplash.com/photo-1600607681015-8d7cfb0435b2",
      country: "Germany",
      description: "An industrial-style loft in the heart of the city.",
      price: 220,
      guests: 3,
      bedrooms: 2,
      beds: 2,
      baths: 1,
      amenities: "WiFi, Gym, City Views",
      profileId: "user_2oTGLobcvLW3sFtiAuxuiRYL4Tq",
    },
    {
      name: "Mystic Cottage",
      tagline: "A magical getaway",
      category: "Cottage",
      image: "https://images.unsplash.com/photo-1533134242443-d4fd215305ad",
      country: "Scotland",
      description: "A whimsical cottage in a remote, tranquil setting.",
      price: 200,
      guests: 4,
      bedrooms: 2,
      beds: 2,
      baths: 1,
      amenities: "Fireplace, Garden, Pet Friendly",
      profileId: "user_2oTGLobcvLW3sFtiAuxuiRYL4Tq",
    },
    {
      name: "Tiny Cabin",
      tagline: "Compact and cozy retreat",
      category: "Tiny",
      image: "https://images.unsplash.com/photo-1470165515910-1f4a8cded6d2",
      country: "Norway",
      description: "A tiny, minimalist cabin perfect for a solo retreat.",
      price: 120,
      guests: 1,
      bedrooms: 1,
      beds: 1,
      baths: 1,
      amenities: "Sauna, Fireplace",
      profileId: "user_2oTGLobcvLW3sFtiAuxuiRYL4Tq",
    },
    {
      name: "Desert Caravan",
      tagline: "Travel through the desert in style",
      category: "Caravan",
      image: "https://images.unsplash.com/photo-1560347876-aeef00ee58a1",
      country: "Egypt",
      description: "A stylish caravan in the heart of the desert.",
      price: 250,
      guests: 3,
      bedrooms: 1,
      beds: 2,
      baths: 1,
      amenities: "WiFi, Air Conditioning, Desert Views",
      profileId: "user_2oTGLobcvLW3sFtiAuxuiRYL4Tq",
    },
    {
      name: "Mountain Lodge",
      tagline: "Rustic lodge in the mountains",
      category: "Lodge",
      image: "https://images.unsplash.com/photo-1560347876-aeef00ee58a1",
      country: "Switzerland",
      description: "A cozy lodge with spectacular mountain views.",
      price: 350,
      guests: 6,
      bedrooms: 3,
      beds: 3,
      baths: 2,
      amenities: "WiFi, Fireplace, Ski Access",
      profileId: "user_2oTGLobcvLW3sFtiAuxuiRYL4Tq",
    },
    {
      name: "Coastal Magic Home",
      tagline: "A beachfront escape with magical vibes",
      category: "Magic",
      image: "https://images.unsplash.com/photo-1600585154842-50fd8dc4a5c7",
      country: "Mexico",
      description: "A mystical beachfront home surrounded by nature.",
      price: 400,
      guests: 6,
      bedrooms: 3,
      beds: 3,
      baths: 3,
      amenities: "WiFi, Pool, Ocean Views",
      profileId: "user_2oTGLobcvLW3sFtiAuxuiRYL4Tq",
    },
    {
      name: "Container Studio",
      tagline: "Minimalistic eco-living",
      category: "Container",
      image: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b",
      country: "Portugal",
      description: "A compact and efficient container studio.",
      price: 100,
      guests: 2,
      bedrooms: 1,
      beds: 1,
      baths: 1,
      amenities: "Solar Power, WiFi, Outdoor Deck",
      profileId: "user_2oTGLobcvLW3sFtiAuxuiRYL4Tq",
    },
    {
      name: "Ski Chalet",
      tagline: "Winter paradise with slopeside access",
      category: "Chalet",
      image: "https://images.unsplash.com/photo-1549421263-4d7c65eb4b86",
      country: "Austria",
      description: "A luxurious chalet with ski-in/ski-out access.",
      price: 500,
      guests: 10,
      bedrooms: 5,
      beds: 6,
      baths: 4,
      amenities: "WiFi, Sauna, Ski Storage",
      profileId: "user_2oTGLobcvLW3sFtiAuxuiRYL4Tq",
    },
  ];

  for (const property of properties) {
    await prisma.property.create({
      data: property,
    });
  }

  console.log("Seeding completed");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
